name: Branch CI
on:
  push:
    branches-ignore:
      - main
    workflow_dispatch:
jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  lint-branch:
    uses: ./.github/workflows/lint.yml