name: Deploy lame-site

on:
  workflow_call:

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install lame-site dependencies
      run: yarn
    
    - name: Build lame-site
      run: yarn build

    - name: Deploy lame-site assets
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.lamemakes.com
        username: ${{ secrets.LAME_SITE_FTP_USERNAME }}
        password: ${{ secrets.LAME_SITE_FTP_PASSWORD }}
        port: ${{ secrets.LAME_SITE_FTP_PORT }}
        protocol: ftps
        local-dir: ./dist/
        server-dir: ./${{ secrets.LAME_SITE_ASSET_PATH }}/
