name: Deploy lame-site

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install lame-site dependencies
      run: yarn
    
    - name: Lint lame-site
      run: yarn build

    - name: Replace old assets
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.LAME_SITE_SSH_ADDRESS }}
        username: ${{ secrets.LAME_SITE_SSH_USERNAME }}
        key: ${{ secrets.LAME_SITE_SSH_KEY }}
        port: ${{ secrets.LAME_SITE_SSH_PORT }}
        script: rm -rf ${{ secrets.LAME_SITE_ASSET_PATH }}/assets/*

    - name: Deploy index.html & favicon.ico assets to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAME_SITE_SSH_ADDRESS }}
        username: ${{ secrets.LAME_SITE_SSH_USERNAME }}
        key: ${{ secrets.LAME_SITE_SSH_KEY }}
        passphrase: ${{ secrets.LAME_SITE_SSH_KEY_PASS }}
        port: ${{ secrets.LAME_SITE_SSH_PORT }}
        source: "dist/*"
        target: ${{ secrets.LAME_SITE_ASSET_PATH }}